### PR TITLE
Casadi as seperate Library

### PR DESCRIPTION
**Pull request by ju6ge**

### CODE REVIEW

**Comment by pariterre** [comment]
@ju6ge 
It is hard for me to judge if things are good, so I am relying on you. Should I merge now?

**Comment by pariterre** [comment]
That said, it is weird that my PR will include all these changes non related to casadi at all...

**Comment by ju6ge** [comment]
well they were merged in another pull request to the main repo, i think they are only displayed because they are new to your fork

**Comment by pariterre** [comment]
Ok, good, so the only non related changes are /rbdl/rbdl in the includes. Should I merge this? I feel that it is not an actual problem

**Comment by ju6ge** [comment]
Great, almost I think i should do a rebase of my branch first removing the duplicate commits, that i just noticed. I update the PR and let you know.

The extra rbdl folder for the include headers was introduced to remove an edge case when including the headers and thereby keeping the includes for casadi and eigen versions seperate.

**Pull request merged**
